# Generated by Django 2.0.13 on 2019-02-26 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessedTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_accessed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_url', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-tag_accessed_on'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_url', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_title', models.TextField()),
                ('blog_published_on', models.DateField()),
                ('blog_modified_on', models.DateField()),
                ('blog_accessed_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_read_duration', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-blog_accessed_on'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('blog_url', models.CharField(max_length=100)),
            ],
        ),
    ]
