# Generated by Django 2.0.13 on 2019-02-28 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessedTag',
            fields=[
                ('tag_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tag_accessed_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-tag_accessed_on'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_title', models.TextField()),
                ('blog_published_on', models.DateField()),
                ('blog_modified_on', models.DateField()),
                ('blog_read_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('tag_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_tags',
            field=models.ManyToManyField(to='MediumCrawler.BlogTag'),
        ),
        migrations.AddField(
            model_name='accessedtag',
            name='blogs',
            field=models.ManyToManyField(to='MediumCrawler.Blog'),
        ),
    ]
